### PR TITLE
Unicode

### PR DESCRIPTION
**Pull request by kmarius**
#### Notes:
- for the string input, converting ascii (non-unicode) to utf16 incurs a performance cost of, say, 10% (depending on the length, of course)
- we can detect non-ascii in the string by checking the highest bit of each character and do the conversion to utf16 only if necessary
- the regex input does not have to be converted, we can simply check for non-bmp (i.e. two code units in utf16) and set a UTF16 flag for the regex compiler. Everything below bmp works fine. I assume there is a tradeoff when activating UTF16.

#### Todo:
- [x] make all unicode work
- [x] add more tests
- [ ] check with asan/valgrind
- [x] tidy up

### CODE REVIEW

**Comment by L3MON4D3** [comment]
Doing the conversion only if necessary sounds like a great idea :+1:

**Comment by L3MON4D3** [comment]
Hi :D
How long do you think you'll need to finish this feature?

It would be awesome if you can get it ready soon-ish, I'd love if luasnip immediately handles unicode correctly.
If it takes some more time, that's alright too, not supporting transforming unicode is not a huge loss IMO

**Comment by kmarius** [comment]
I think I does work correctly, but I don't have a good idea on what to test yet. There are some lists like https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt and https://www.cl.cam.ac.uk/~mgk25/ucs/examples/quickbrown.txt. I would also like some malformed utf-8. This is arguably more important than being correct because a crash here will crash neovim.

**Comment by L3MON4D3** [comment]
Good point!

I guess quickjs's applying a regex to unicode is well tested, so there would need to be tests for transforming utf8 to utf16 (and back)?

**Comment by kmarius** [comment]
@L3MON4D3 Ok, feeding random bytes into `lre_compile` *will* crash when repeated tens of thousands of times. I think checking for valid utf8 can be done if we don't trust the user. Stopping the conversion from utf8 to utf16 prevents crashing during matching. Would you expect some kind of error in that case? Or just no matches?

**Comment by L3MON4D3** [comment]
An error sounds appropriate :+1:
Better to distinguish between error and no match (we should just log errors).

**Comment by kmarius** [comment]
I went with returning `nil, err` on error.

For the crashing, it looks like `lre_compile` segfaults if the input string contains `0xfd`. This byte used to indicate the beginning of a six byte sequence which is unneeded and was removed. Valid unicode can not contain `0xfd` so we can check for that.

**Comment by L3MON4D3** [comment]
Nice, that sounds good
Looking at the spec, `0xfc`indicate six bytes as well, does it also crash?

**Comment by kmarius** [comment]
No, only `0xfd`, and only in combination with other non-ascii chars. I also cannot reproduce it outside of the lua/luajit context. I think I will merge #8 and then this PR later today, seems easier in this order.

**Comment by L3MON4D3** [comment]
> No, only 0xfd, and only in combination with other non-ascii chars. 

Okay, that's good I guess :D

> I think I will merge #8 and then this PR later today, seems easier in this order.

Niiice, TY for getting it done this quickly :heart:

**Pull request merged**
